### ISSUE TITLE
Add current location button

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/react-select-geocoder#3]

**Comment by landonreed** [comment]
Things left to do:

- [ ] render icons with geolocate option
- [ ] get location before user clicks geolocate option?
- [ ] provide alternative method for getting location (e.g., button click instead of option)

**Comment by trevorgerhardt** [comment]
@landonreed a few things

1. Are icons necessary? I would say let's skip them in the first iteration. Along with that we should allow setting all of the messages ("Use my location", "Finding location", etc.) as props and use the English version as default props. Speaking of props, don't forget to add the new `PropType` definitions!

2. I think we hashed this out already but I'll reiterate here. Asking for a user's location before they specifically click to "use their location" is a big no-no. Rearranging the geolocation, as stated [here](https://github.com/conveyal/react-select-geocoder/commit/1e13e32aaae0ed86187d145b4b989c9af56d064b#commitcomment-20829794), should speed it up.

3. Let's keep it simple. CityMapper is really well designed and they went with it as an option in the dropdown once you select the search box. Adding any more buttons inside the search box would be difficult (due to our usage of `react-select`) and clutter it IMO.

<img width="335" alt="screenshot 2017-02-10 09 50 35" src="https://cloud.githubusercontent.com/assets/776780/22820395/db551304-ef76-11e6-8374-8cb94b0786ae.png">
