### ISSUE TITLE
Default styling on search box makes it tiny!

### ISSUE THREAD

**Issue by hjmccain** [conveyal/react-select-geocoder#33]
If there's an easy way around this that I haven't found, let me know 😄 I have tried a few ways of accessing the element ( `input role="combobox"` ), but my styling is always overridden by the default styling, which gives the search box a width of only 5px.

**Comment by trevorgerhardt** [comment]
@hjmccain this is based off of [react-select](https://github.com/JedWatson/react-select). Make sure you include the `react-select` stylesheet when using! See the example here: https://github.com/conveyal/react-select-geocoder/blob/master/index.html#L6
