### ISSUE TITLE
Constant loading

### ISSUE THREAD

**Issue by j1mie** [conveyal/react-select-geocoder#41]
The select geocoder correctly loads results, but after focussing on the input, the loading spinner constantly displays, and the dropdown displays "loading", even with no query. Guessing this is an issue with a dependency, as I'm only seeing this on a fresh npm install.

**Comment by trevorgerhardt** [comment]
Interesting, can you produce a broken test for this issue via a pull request to show the broken behavior?

**Comment by j1mie** [comment]
Can't seem to replicate it using this repo - however I've installed the package with a fresh create-react-app instance here: https://github.com/j1mie/geocoder-test and you can see issue.

**Comment by trevorgerhardt** [comment]
Ok. `create-react-app` is webpack based and our build tool for this project is `browserify` based. If you'd like to attempt to make it this webpack compatible or produce a broken test suite run with webpack then by all means please open a pull request doing so!
